/*
    SQL code will drop and create user table
*/

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Adding unique constraint on email
    CONSTRAINT users_email_unique UNIQUE (email),
    
    -- Optional: Add a unique constraint on combination of first and last name
    CONSTRAINT users_name_unique UNIQUE (first_name, last_name),
    
    -- Email format check
    CONSTRAINT chk_email_format CHECK (email LIKE '%@%.%')
);



INSERT INTO users (first_name, last_name, email, password_hash, role) 
VALUES 
('Jose', 'User', 'jose@yahoo.com', 'csc481', 'organizer'),
('Test', 'User', 'test@test.com', 'test123', 'attendee'),
('Admin', 'Admin', 'admin@example.com', 'admin123', 'admin'),
('Stitch', 'Alien', 'StiAlien@disney.world', 'disney123', 'attendee'),
('Pinocchio', 'Puppet', 'PinPuppet@disney.world', 'disney124', 'attendee'),
('Jiminy', 'Cricket', 'JimCricket@disney.world', 'disney125', 'attendee'),
('Flounder', 'Fish', 'FloFish@disney.world', 'disney126', 'attendee'),
('Jasmine', 'Human', 'JasHuman@disney.world', 'disney127', 'attendee'),
('Merida', 'Human', 'MerHuman@disney.world', 'disney128', 'attendee'),
('Zazu', 'Bird', 'ZazBird@disney.world', 'disney129', 'attendee'),
('Esmeralda', 'Human', 'EsmHuman@disney.world', 'disney130', 'attendee'),
('Megara', 'Human', 'MegHuman@disney.world', 'disney131', 'attendee'),
('Buzz', 'Lightyear', 'BuzLightyear@disney.world', 'disney132', 'attendee'),
('Timon', 'Meerkat', 'TimMeerkat@disney.world', 'disney133', 'organizer'),
('Prince', 'Eric', 'PriEric@disney.world', 'disney134', 'organizer'),
('Piglet', 'Pig', 'PigPig@disney.world', 'disney135', 'organizer'),
('Aladdin', 'Human', 'AlaHuman@disney.world', 'disney136', 'organizer'),
('Jack-Jack', 'Parr', 'JacParr@disney.world', 'disney137', 'organizer'),
('Pumbaa', 'Warthog', 'PumWarthog@disney.world', 'disney138', 'organizer'),
('Captain', 'Hook', 'CapHook@disney.world', 'disney139', 'organizer'),
('Marlin', 'Fish', 'MarFish@disney.world', 'disney140', 'organizer'),
('Tinker', 'Bell', 'TinBell@disney.world', 'disney141', 'organizer'),
('Beast', 'Beast', 'BeaBeast@disney.world', 'disney142', 'organizer'),
('Cruella', 'de Vil', 'Crude Vil@disney.world', 'disney143', 'organizer'),
('Roz', 'Monster', 'RozMonster@disney.world', 'disney144', 'organizer'),
('Goofy', 'Dog', 'GooDog@disney.world', 'disney145', 'organizer'),
('Kristoff', 'Human', 'KriHuman@disney.world', 'disney146', 'attendee'),
('Donald', 'Duck', 'DonDuck@disney.world', 'disney147', 'attendee'),
('Hades', 'God', 'HadGod@disney.world', 'disney148', 'attendee'),
('Pongo', 'Dog', 'PonDog@disney.world', 'disney149', 'attendee'),
('Eeyore', 'Donkey', 'EeyDonkey@disney.world', 'disney150', 'attendee'),
('Rapunzel', 'Human', 'RapHuman@disney.world', 'disney151', 'attendee'),
('Tarzan', 'Human', 'TarHuman@disney.world', 'disney152', 'attendee'),
('Snow', 'White', 'SnoWhite@disney.world', 'disney153', 'attendee'),
('Rafiki', 'Mandrill', 'RafMandrill@disney.world', 'disney154', 'attendee'),
('Quasimodo', 'Human', 'QuaHuman@disney.world', 'disney155', 'attendee'),
('Dash', 'Parr', 'DasParr@disney.world', 'disney156', 'attendee'),
('Lumiere', 'Candelabra', 'LumCandelabra@disney.world', 'disney157', 'attendee'),
('Genie', 'Genie', 'GenGenie@disney.world', 'disney158', 'attendee'),
('Cinderella', 'Human', 'CinHuman@disney.world', 'disney159', 'attendee'),
('Mad', 'Hatter', 'MadHatter@disney.world', 'disney160', 'attendee'),
('Olaf', 'Snowman', 'OlaSnowman@disney.world', 'disney161', 'attendee'),
('Minnie', 'Mouse', 'MinMouse@disney.world', 'disney162', 'attendee'),
('Peter', 'Pan', 'PetPan@disney.world', 'disney163', 'attendee'),
('Mrs.', 'Potts', 'MrsPotts@disney.world', 'disney164', 'attendee'),
('Daisy', 'Duck', 'DaiDuck@disney.world', 'disney165', 'attendee'),
('Scar', 'Lion', 'ScaLion@disney.world', 'disney166', 'attendee'),
('Mushu', 'Dragon', 'MusDragon@disney.world', 'disney167', 'attendee'),
('Elastigirl', 'Human', 'ElaHuman@disney.world', 'disney168', 'attendee'),
('Simba', 'Lion', 'SimLion@disney.world', 'disney169', 'attendee'),
('Timothy', 'Q. Mouse', 'TimQ. Mouse@disney.world', 'disney170', 'attendee'),
('Tigger', 'Tiger', 'TigTiger@disney.world', 'disney171', 'attendee'),
('Bambi', 'Deer', 'BamDeer@disney.world', 'disney172', 'attendee'),
('Mike', 'Wazowski', 'MikWazowski@disney.world', 'disney173', 'attendee'),
('Boo', 'Human', 'BooHuman@disney.world', 'disney174', 'attendee'),
('Jafar', 'Human', 'JafHuman@disney.world', 'disney175', 'attendee'),
('Thumper', 'Rabbit', 'ThuRabbit@disney.world', 'disney176', 'attendee'),
('Roger', 'Radcliffe', 'RogRadcliffe@disney.world', 'disney177', 'attendee'),
('Shan', 'Yu', 'ShaYu@disney.world', 'disney178', 'attendee'),
('Woody', 'Toy', 'WooToy@disney.world', 'disney179', 'attendee'),
('Mater', 'Car', 'MatCar@disney.world', 'disney180', 'attendee'),
('Li', 'Shang', 'LiShang@disney.world', 'disney181', 'attendee'),
('Wendy', 'Darling', 'WenDarling@disney.world', 'disney182', 'attendee'),
('Sultan', 'Human', 'SulHuman@disney.world', 'disney183', 'attendee'),
('Mickey', 'Mouse', 'MicMouse@disney.world', 'disney184', 'attendee'),
('Lightning', 'McQueen', 'LigMcQueen@disney.world', 'disney185', 'attendee'),
('Winnie', 'the Pooh', 'Winthe Pooh@disney.world', 'disney186', 'attendee'),
('Hercules', 'Demigod', 'HerDemigod@disney.world', 'disney187', 'attendee'),
('Chip', 'Teacup', 'ChiTeacup@disney.world', 'disney188', 'attendee'),
('Tiana', 'Human', 'TiaHuman@disney.world', 'disney189', 'attendee'),
('Gaston', 'Human', 'GasHuman@disney.world', 'disney190', 'attendee'),
('Nemo', 'Fish', 'NemFish@disney.world', 'disney191', 'attendee'),
('Cogsworth', 'Clock', 'CogClock@disney.world', 'disney192', 'attendee'),
('Alice', 'Human', 'AliHuman@disney.world', 'disney193', 'attendee'),
('Violet', 'Parr', 'VioParr@disney.world', 'disney194', 'attendee'),
('Claude', 'Frollo', 'ClaFrollo@disney.world', 'disney195', 'attendee'),
('LeFou', 'Human', 'LeFHuman@disney.world', 'disney196', 'attendee'),
('Mufasa', 'Lion', 'MufLion@disney.world', 'disney197', 'attendee'),
('Randall', 'Boggs', 'RanBoggs@disney.world', 'disney198', 'attendee'),
('Lilo', 'Human', 'LilHuman@disney.world', 'disney199', 'attendee'),
('Queen of', 'Hearts', 'QueHearts@disney.world', 'disney200', 'attendee'),
('Pocahontas', 'Human', 'PocHuman@disney.world', 'disney201', 'attendee'),
('Jane', 'Porter', 'JanPorter@disney.world', 'disney202', 'attendee'),
('Jessie', 'Toy', 'JesToy@disney.world', 'disney203', 'attendee'),
('Ursula', 'Sea Witch', 'UrsSea Witch@disney.world', 'disney204', 'attendee'),
('Abu', 'Monkey', 'AbuMonkey@disney.world', 'disney205', 'attendee'),
('Ariel', 'Mermaid', 'AriMermaid@disney.world', 'disney206', 'attendee'),
('Mr.', 'Incredible', 'Mr.Incredible@disney.world', 'disney207', 'attendee'),
('Perdita', 'Dog', 'PerDog@disney.world', 'disney208', 'attendee'),
('Iago', 'Parrot', 'IagParrot@disney.world', 'disney209', 'attendee'),
('Sven', 'Reindeer', 'SveReindeer@disney.world', 'disney210', 'attendee'),
('Sully', 'Monster', 'SulMonster@disney.world', 'disney211', 'attendee'),
('Moana', 'Human', 'MoaHuman@disney.world', 'disney212', 'attendee'),
('Dory', 'Fish', 'DorFish@disney.world', 'disney213', 'attendee'),
('Remy', 'Rat', 'RemRat@disney.world', 'disney214', 'attendee'),
('Belle', 'Human', 'BelHuman@disney.world', 'disney215', 'attendee'),
('Mulan', 'Human', 'MulHuman@disney.world', 'disney216', 'attendee'),
('Sebastian', 'Crab', 'SebCrab@disney.world', 'disney217', 'attendee'),
('Anna', 'Human', 'AnnHuman@disney.world', 'disney218', 'attendee'),
('Anita', 'Radcliffe', 'AniRadcliffe@disney.world', 'disney219', 'attendee'),
('Dumbo', 'Elephant', 'DumElephant@disney.world', 'disney220', 'attendee'),
('Aurora', 'Human', 'AurHuman@disney.world', 'disney221', 'attendee'),
('Elsa', 'Human', 'ElsHuman@disney.world', 'disney222', 'attendee');



